name: CI

on: [push]

jobs:
  sast_scan:
    name: Run Bandit
    runs-on: ubuntu-latest

    steps:
     - name: Checkout Code
       uses: actions/checkout@v2

     - name: Setup python
       uses: actions/setup-python@v2
       with:
         python-version: 3.8
     - name: Install bandit
       run: pip install bandit
     - name: run bandit
       run: bandit -r -ll -ii . -f json  -o bandit-report.json
       
     - name: Upload
       uses: actions/upload-artifact@v3
       if: always()
       with:
         name: bandit-findings
         path: bandit-report.json
    
